vlib work
vcom -work work runtime.vhd
vcom -work work runtime.vhd
vcom -work work runtime.vhd
vcom -work work IOShuvalkin.vhd
vcom -work work IOShuvalkin.vhd
vcom -work work IOShuvalkin.vhd
vcom -work work arrayAsAliasTrimmers.vhd
vcom -work work types.vhd
vcom -work work ext_TopFromFile.vhd
vcom -work work ext_TopToFile.vhd
vcom -work work ext_TopToFile1.vhd
vcom -work work ext_TopVarToLog.vhd
vcom -work work ext_TopRdyCutStp0Isuint10BufFull.vhd
vcom -work work proc_TopRdyCutStp0Isuint10.vhd
vcom -work work proc_TopLInserterStp0Isint16.vhd
vcom -work work proc_TopPipeStp0Isint16.vhd
vcom -work work RenamerWrapper_Top.vhd
vcom -work work proc_TopMain.vhd
vcom -work work proc_Top.vhd
vcom -work work testTop.vhd
